### PR TITLE
Swap TagGoogle in StorageManagerGoogle for proper APK

### PR DESCRIPTION
**Pull request by SpasilliumNexus**
I have absolutely no idea how I've messed that one up...

### CODE REVIEW

**Comment by NicholasBuse** [comment]
Do you look @ Android Police? If not, you should!

**Comment by SpasilliumNexus** [comment]
Yup, every morning! I saw the article, and the real shout out goes out to you guys for having this project available! I like it so much that I have to give back in some kind of way, and contributing to help keep it alive is it! 😁

**Comment by NicholasBuse** [comment]
Was there a StorageManagerGoogle APK to commit too? or is the 8.1.0 still current?

**Comment by SpasilliumNexus** [comment]
I don't remember how or why I did it, but I placed the TagGoogle APK inside the StorageManagerGoogle folder. This pull removes the TagGoogle APK and replaces it with the proper StorageManagerGoogle APK from the taimen factory image.

[Screenshot of the proper APK and its info](https://i.imgur.com/xXLrLOx.png)

**Pull request merged**
