### PR TITLE
Pixel Launcher all-21 ODR-4023749 (204)

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by mfonville** [comment]
Where did you obtain this apk? Or did you de-odex it yourself?

**Comment by alviteri** [comment]
Apkmirror ... It seems not the best but works ..

**Comment by mfonville** [comment]
Hmm, I wonder what the source-diskimage for this was, on the Marlin-image I can only find an odexed version :-/

**Comment by mfonville** [comment]
For now I think we will jus stick to the version found in the Play Store

**Comment by alviteri** [comment]
Honestly I can't answer you but ... This let me user adaptive apps icons ... When round icons overlay is not set

**Comment by alviteri** [comment]
You can see a screen here 

https://github.com/opengapps/aosp_build/pull/147

**Pull request closed without merging**
