### PR TITLE
Add Oreo (26) SetupWizard

### PR DESCRIPTION
**Pull request by jumoog**

### CODE REVIEW

**Comment by jumoog** [comment]
otherwise SetupWizard will crash under Oreo

**Comment by alviteri** [comment]
hi @jumoog what kind of crash you mean ?

**Comment by jumoog** [comment]
i had a crash with 225

**Comment by alviteri** [comment]
using aosp_build system or zip ? my problem is downloads from playstore works randomly or settings - apps - Google Play Store - finish process then open play store again ..... but never seen crashes with SetupWizard since my first oreo build 2 days after code was released

**Comment by alviteri** [comment]
@NicholasBuse +1 for this .... starting to get FC with SetupWizard

**Comment by alviteri** [comment]
seem time to look away ... seem opengapps will remain available until nougat .....

**Comment by mfonville** [comment]
Unfortunately I have some things going on in my personal life that severely limit my time to work at OpenGApps, but I have been able to take a look at the Oreo images and will probably provide soon 8.0 builds

**Comment by mfonville** [comment]
See https://github.com/opengapps/all/commit/45c5900c54620fbe844240371accd73177df3898

**Pull request closed without merging**
