### PR TITLE
Nexus Launcher & wallpaper

### PR DESCRIPTION
**Pull request by alviteri**
both are needed in same zip or aosp_build or there are FC

Nexus Launcher 7.1-3231428(26)
Wallpaper wallpaper.20160809_RC01(13055056)

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@mfonville there is hope for this?

**Comment by mfonville** [comment]
Hey, sorry, had not paid attention to this PR yet.

Can you explain exactly why these are necessary for in aosp_build?

**Comment by alviteri** [comment]
are not necessary because we have google launcher but there is a good option against that .... just that

**Comment by mfonville** [comment]
hmm, I do not really understand your point.

Anyhow, I assume these are from leaked 7.1, and I don't want to merge those until we get official 7.1 images.

**Comment by alviteri** [comment]
ok

**Comment by mfonville** [comment]
Still thanks for the contributing, and when the official ones arrive, feel free to PR it ;-)

**Pull request closed without merging**
