### PR TITLE
Oreo update

### PR DESCRIPTION
**Pull request by nezorflame**
Update apps for SDK 27.

	etc/permissions/com.google.android.dialer.support.xml
	app/com.android.facelock/27/
	app/com.google.android.calendar/17/480/
	app/com.google.android.ext.shared/27/
	app/com.google.android.syncadapters.contacts/27/
	framework/27/
	priv-app/com.google.android.backuptransport/27/
	priv-app/com.google.android.feedback/27/
	priv-app/com.google.android.gsf/27/
	priv-app/com.google.android.onetimeinitializer/27/
	priv-app/com.google.android.partnersetup/27/
	priv-app/com.google.android.setupwizard.default/27/
	priv-app/com.google.android.tag/27/

### CODE REVIEW

**Comment by nezorflame** [comment]
@mfonville @NicholasBuse

**Comment by SpasilliumNexus** [comment]
We might need this Config Updater too as I remember it being one of the 8.0.0 files listed during make: https://www.apkmirror.com/apk/google-inc/configupdater/configupdater-8-1-0-release/configupdater-8-1-0-android-apk-download/

I'll definitely look into this pull as soon as I get back home.

**Comment by nezorflame** [comment]
@SpasilliumNexus added more.

**Comment by SpasilliumNexus** [comment]
@nezorflame Awesome! As soon as I get off of work I'll also dig around the images for files we may need.

**Comment by nezorflame** [comment]
I'll also post updates for arm and arm64 from latest LineageOS-approved GApps in coming minutes.

**Comment by nezorflame** [comment]
https://github.com/opengapps/arm/pull/5 and https://github.com/opengapps/arm64/pull/3

**Comment by nezorflame** [comment]
Should be good now.

**Comment by nezorflame** [comment]
@NicholasBuse @mfonville need your review on this, all this stuff is confirmed as working (at least on beta quality) by many users.

**Comment by NicholasBuse** [comment]
@nezorflame , First, thanks for championing this update.

Here are a few items that I see to address:

1. Not sure what "app/com.google.android.calendar/17/480/2015475782.apk" is part of this PR.
2. I don't think we should downgrade the launcher: app/com.google.android.launcher/16/nodpi/104002.apk-->app/com.google.android.launcher/16/nodpi/104001.apk.
3. StorageManager (priv-app/com.google.android.storagemanager/24/nodpi/27.apk) needs to be in the SDK26 (or SDK27) folder. The older one in the SDK24 folder has to stay there for Nougat support. I know that it says it supports SDK24, but there were issues (see: https://github.com/opengapps/all/commit/2b4fb8bdc34c32b95d589bdaa48b23bc44116e17)

If you could correct these, it would help me get to merging. (will review others now)

**Comment by nezorflame** [comment]
Closing in favor of https://github.com/opengapps/all/pull/17

**Pull request closed without merging**
